# Generated by Django 3.0.5 on 2020-06-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrate',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
