# Generated by Django 3.0.5 on 2020-06-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsite', '0003_auto_20200630_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrate',
            name='employee_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payrollsite.Employee'),
        ),
    ]
