# Generated by Django 3.0.5 on 2020-06-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollsite', '0004_auto_20200630_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_emp_id',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
